### ISSUE TITLE
Improve API for writing buffer to allow for files that cannot be contained in memory

### ISSUE THREAD

**Issue by nbeadman** [abbeycode/UnzipKit#9]
The current `-[UZKArchive writeIntoBuffer:CRC:fileDate:compressionMethod:password:overwrite:error:block:]` method requires that the CRC for the entire file be calculated before the method is called.

In all of the documentation/sample code this is done by creating an NSData of an entire file contents and then running that through `crc32()`.

If you are going to create an NSData then why not use `-[UZKArchive writeData:filePath:fileDate:compressionMethod:password:overwrite:progress:error:]` ?

**Comment by abbeycode** [comment]
Thanks for the feedback. I'll take a look when I have a chance, and let you know what I find. Let me know if you have any suggestions.

**Comment by abbeycode** [comment]
It looks like I should be able to calculate the CRC's from multiple chunks of data using the `crc32_combine()` method. I'll let you know if I can get something working.

**Comment by nbeadman** [comment]
I see two possible approaches:

* add API that takes an `NSInputStream` and calculates the CRC as it goes
* update the `NSData` to handle very large memory mapped files (created using `NSDataReadingUncached + NSDataReadingMappedAlways`

Thinking about it, there is a possibility that the current `NSData` API will fail with NSData that contain more than 4G of data because `crc32()` takes a uInt aka `unsigned int` whereas `-[NSData length]` returns a `unsigned long` if compiling x86_64

**Comment by nbeadman** [comment]
`crc32_combine()` will help but you can call `crc32()` with the first parameter being the current CRC anyway. The bigger issue is the API.

**Comment by abbeycode** [comment]
I implemented a solution in the issue9 branch. Can you take a look and see if that will work for you?

**Comment by nbeadman** [comment]
The solution you have implemented works fine.

My only issue is that there is no way for the action block to provide an error. In my case I am going to use a NSInputStream and am reading in to a buffer and then calling the write block. However, if the stream read fails then there is no way to terminate the operation and provide an error (which could be possibly be used in a NSUnderlyingErrorKey.

**Comment by abbeycode** [comment]
Good call! That was a glaring oversight. I've added it to the issue9 branch. Once it looks good to you, I can merge to trunk and cut a new CocoaPods release.

**Comment by nbeadman** [comment]
That was actually very close (all except parameter names!) to the pull-request I was just about to submit.

**Comment by abbeycode** [comment]
Very cool, sorry for the wasted effort. I'll close out the issue once I release it out. Should be soon.

**Comment by nbeadman** [comment]
Don't worry about it all. UnzipKit is great and the fact that it is under active development seals the deal. I am getting more familiar with it and next time I won't ask for help but submit a pull-request :-)

**Comment by abbeycode** [comment]
Awesome, good to have you onboard. I just pushed v1.3 to CocoaPods, so you can give it a shot there.

**Comment by nbeadman** [comment]
Just a data point, I don't use CocoaPods just a git submodule. Have you considered Carthage?

https://github.com/Carthage/Carthage

**Comment by abbeycode** [comment]
Interesting, I hadn't heard of it before. I take it that UnzipKit is already Carthage-compatible?

**Comment by nbeadman** [comment]
That I don't know but I think it would be. Carthage wants to build frameworks which UnzipKit already is. This is something that is on my list of things to look at. If you have time the following talk gives you a relatively quick rundown:

http://realm.io/news/swift-dependency-management-with-carthage/
https://github.com/jspahrsummers/carthage-talk

You can either watch the video or read the transcript.

**Comment by aventurella** [comment]
+1 for Carthage support

**Comment by SkiesOFF** [comment]
Is it possible to implement writeIntoBuffer with password by combining the CRC? Even if it takes 2x more time (reading the file to get the CRC and reading again to write).

**Comment by abbeycode** [comment]
What is your reason for using the buffer-based method in the first place, instead of the NSData one?

**Comment by SkiesOFF** [comment]
In my app users have the possibility to zip their files. It would be nice if they can create the zip with password. Since is user's files, i don't know how big the files might be.

**Comment by abbeycode** [comment]
To answer your question, that is just an informational log statement. You are using it correctly. Open an issue for it and I'll take care of it.

Regarding zipping with a password, you can't write into a buffer and protect it with a password because the CRC of the file must be known ahead of time when using a password. I recommend setting the `password` field on the archive and then using `-writeData:filePath:error:` to add the files.

**Comment by SkiesOFF** [comment]
Thanks, it's ok, i don't think this is an issue.

By reading the entire file first to calculate the CRC and than read again to write is not possible?

**Comment by abbeycode** [comment]
But as soon as you read the entire file into memory, why not make an NSData out of it? The buffered write API is meant for when the file in question is too big to have in memory all at once, or is not known up front. Does that make sense?

And with the log message, I agree that it's annoying, and it can be handled better (or at least worded better).

**Comment by SkiesOFF** [comment]
Yes, i understand. I thought the CRC could be calculated using chunks, not needing the entire file in memory.

**Comment by abbeycode** [comment]
Sorry, I think you're misunderstanding. Every file written to the archive needs a CRC, which is written after the data is written. This works when writing an NSData or when streaming the file into the archive. UnzipKit calculates the CRC for a buffered write one chunk at a time, as you describe.

The problem, [as described in this Stack Overflow answer](http://stackoverflow.com/a/30968252) is that the zlib library requires the CRC up front when writing an encrypted file. Many Zip readers read the encrypted CRC from the header to verify that the given password is correct. The fix for Issue #12 involved always passing the CRC up front when starting to write a file. Until that point, the method you asked about could take a Password argument, but it would produce incorrect results.

You can see [on this line](https://github.com/abbeycode/UnzipKit/blob/master/Source/UZKArchive.m#L827) that the CRC is still calculated when the file is streamed (since addressing this issue that you commented on). But, it has to pass `0` for the up-front CRC, since it's not known, which gets passed when opening the Zip file [on this line](https://github.com/abbeycode/UnzipKit/blob/master/Source/UZKArchive.m#L1251).

Does that make sense now?

**Comment by SkiesOFF** [comment]
Yes, sorry, I think i was not clear in my first comment when i said "reading" i really meant "streaming" or "reading in chunks". 

My ideia is to first stream the file **just** to calculate the CRC and than stream it (writeIntoBuffer) **again** using the CRC calculated.

Is it possible, since i would have the CRC before start writing?

**Comment by abbeycode** [comment]
I'm not understanding your use case. If you (a) need to stream a file and (b) need to encrypt it in the archive, this is what I would say you should do:

``` Objective-c
UZKArchive *archive = // Create your archive
archive.password = // The password your user entered

while (/* there is data */) {
    // Accumulate your data
}

NSData *wholeData = [NSData dataWithBytes:yourData
                                   length:dataLength];

NSError *error = nil;
BOOL success = [archive writeData:wholeData
                         filePath:@"filenameIn/archive/data.dat"
                            error:&error];

if (!success) {
    NSLog(@"Error writing file: %@", error);
    [NSApp presentError:error];
}
```

Where does that fall short for you?

**Comment by SkiesOFF** [comment]
File can be too big to have in memory all at once.
