### ISSUE TITLE
Performance issues after upgrading to v1.9

### ISSUE THREAD

**Issue by KorolkovAnton163** [abbeycode/UnzipKit#98]
After the upgrade, performance issues appeared. A little research was done and revealed that this is due to logging. I would like to see the ability to turn off logging.

**Comment by abbeycode** [comment]
Have you tried configuring the logging to either make it less verbose or disable it altogether, as described [in the Readme](https://github.com/abbeycode/UnzipKit#logging)? The `default` logging level should result in no messages being output, and I've personally seen this speed up running UnzipKit in Xcode.

**Comment by UksusoFF** [comment]
@abbeycode yes changing log level speed up working. But we need any way to change this level in xcode projects.
It's really not conveniently change this on each developers machine.

Related issue: #75

**Comment by abbeycode** [comment]
In your build scheme, can you try setting the `OS_ACTIVITY_MODE` environment variable to `disable`? If that works, I'll make this ticket a documentation request to add this instruction to the readme.

**Comment by KorolkovAnton163** [comment]
Sorry it took so long did not answer, you proposed option works, but not for us as it is necessary to affix each developer. I would like to have the option of modifying or disabling logging during assembly.

**Comment by KorolkovAnton163** [comment]
Yes, end users do not have performance problems, but I would like to see the ability to disable logging by the parameter in the build settings, because we often have to run the build for development on non-developer computers (eg QA), and in addition, it completely disables system logging, which in our case is unacceptable. We will be very grateful if you make this functionality.

**Comment by abbeycode** [comment]
Sorry, I'm trying to understand exactly what your situation is to propose the best solution. Is it slowing down your unit tests or something? If so, you can update the environment variables in the scheme you use for unit testing. If you want to disable only UnzipKit's logs, you can run the command below, as mentioned in the readme:

    sudo log config --mode "level:default" --subsystem com.abbey-code.UnzipKit

I'm doing this in the UnzipKit CI script, since it was blowing past the size limit on the logs. I'm able to set it to a different level as needed that way, and it doesn't affect other subsystems within your app.

**Comment by KorolkovAnton163** [comment]
We consulted and decided that the option of adding a command to a script that collects dependencies and running tests is suitable for us. Thank you for the answer. I close Issue.
